constants:
  G_m3kg1s2: 6.67430e-11
  c_ms: 2.99792458e8
  Msun_kg: 1.98847e30
  kpc_m: 3.085677581491367e19

stellar_ML_36:
  ref: 1.0
  adopted: 0.5

helium_factor: 1.33

samples:
  strict:   {Q_max: 3, inc_min: 30, inc_max: 80}
  extended: {Q_max: 3, inc_min: 15, inc_max: 85}

bootstrap: {n_iter: 20000, seed: 12345}

binning:
  hist_bin_dex: 0.2
