name: Reproduce pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run pipeline
        run: |
          PYTHONPATH=. python scripts/run_all.py
          PYTHONPATH=. python scripts/make_samples.py
          PYTHONPATH=. python scripts/summary_stats.py
          PYTHONPATH=. python scripts/fit_mass_compactness.py
      - name: Upload artifacts (summary + tables)
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            outputs/summary/*.json
            outputs/tables/*CLEAN_*.csv
            outputs/tables/SPARC_lambda_quickcheck.csv
